const countriesData = [
  {
    country: 'India',
    currency: 'INR',
    currencyName: 'Indian Rupee',
    symbol: '₹',
  },
  {
    country: 'United States',
    currency: 'USD',
    currencyName: 'US Dollar',
    symbol: '$',
  },
  {
    country: 'United Arab Emirates',
    currency: 'AED',
    currencyName: 'United Arab Emirates Dirham',
    symbol: 'د.إ',
  },
  {
    country: 'Afghanistan',
    currency: 'AFN',
    currencyName: 'Afghan Afghani',
    symbol: '؋',
  },
  {
    country: 'Antigua and Barbuda',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    symbol: '$',
  },
  {
    country: 'Albania',
    currency: 'ALL',
    currencyName: 'Albanian Lek',
    symbol: 'L',
  },
  {
    country: 'Armenia',
    currency: 'AMD',
    currencyName: 'Armenian Dram',
    symbol: '֏',
  },
  {
    country: 'Netherlands Antilles',
    currency: 'ANG',
    currencyName: 'Netherlands Antillean Guilder',
    symbol: 'ƒ',
  },
  {
    country: 'Angola',
    currency: 'AOA',
    currencyName: 'Angolan Kwanza',
    symbol: 'Kz',
  },
  {
    country: 'Antarctica',
    currency: 'AQD',
    currencyName: 'Antarctican Dollar',
    symbol: '$',
  },
  {
    country: 'Argentina',
    currency: 'ARS',
    currencyName: 'Argentine Peso',
    symbol: '$',
  },
  {
    country: 'Australia',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    symbol: '$',
  },
  {
    country: 'Azerbaijan',
    currency: 'AZN',
    currencyName: 'Azerbaijani Manat',
    symbol: '₼',
  },
  {
    country: 'Bosnia and Herzegovina',
    currency: 'BAM',
    currencyName: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
  },
  {
    country: 'Barbados',
    currency: 'BBD',
    currencyName: 'Barbadian Dollar',
    symbol: '$',
  },
  {
    country: 'Bangladesh',
    currency: 'BDT',
    currencyName: 'Bangladeshi Taka',
    symbol: '৳',
  },
  {
    country: 'Belgium',
    currency: 'XOF',
    currencyName: 'West African CFA Franc',
    symbol: 'Fr',
  },
  {
    country: 'Bulgaria',
    currency: 'BGN',
    currencyName: 'Bulgarian Lev',
    symbol: 'лв',
  },
  {
    country: 'Bahrain',
    currency: 'BHD',
    currencyName: 'Bahraini Dinar',
    symbol: '.د.ب',
  },
  {
    country: 'Burundi',
    currency: 'BIF',
    currencyName: 'Burundian Franc',
    symbol: 'Fr',
  },
  {
    country: 'Bermuda',
    currency: 'BMD',
    currencyName: 'Bermudian Dollar',
    symbol: '$',
  },
  {
    country: 'Brunei',
    currency: 'BND',
    currencyName: 'Brunei Dollar',
    symbol: '$',
  },
  {
    country: 'Bolivia',
    currency: 'BOB',
    currencyName: 'Bolivian Boliviano',
    symbol: 'Bs',
  },
  {
    country: 'Brazil',
    currency: 'BRL',
    currencyName: 'Brazilian Real',
    symbol: 'R$',
  },
  {
    country: 'Bahamas',
    currency: 'BSD',
    currencyName: 'Bahamian Dollar',
    symbol: '$',
  },
  {
    country: 'Norway',
    currency: 'NOK',
    currencyName: 'Norwegian Krone',
    symbol: 'kr',
  },
  {
    country: 'Botswana',
    currency: 'BWP',
    currencyName: 'Botswana Pula',
    symbol: 'P',
  },
  {
    country: 'Belarus',
    currency: 'BYR',
    currencyName: 'Belarusian Ruble',
    symbol: 'Br',
  },
  {
    country: 'Belize',
    currency: 'BZD',
    currencyName: 'Belize Dollar',
    symbol: '$',
  },
  {
    country: 'Canada',
    currency: 'CAD',
    currencyName: 'Canadian Dollar',
    symbol: '$',
  },
  {
    country: 'Democratic Republic of the Congo',
    currency: 'CDF',
    currencyName: 'Congolese Franc',
    symbol: 'Fr',
  },
  {
    country: 'Switzerland',
    currency: 'CHF',
    currencyName: 'Swiss Franc',
    symbol: 'Fr',
  },
  {
    country: 'Chile',
    currency: 'CLP',
    currencyName: 'Chilean Peso',
    symbol: '$',
  },
  {
    country: 'China',
    currency: 'CNY',
    currencyName: 'Chinese Yuan',
    symbol: '¥',
  },
  {
    country: 'Colombia',
    currency: 'COP',
    currencyName: 'Colombian Peso',
    symbol: '$',
  },
  {
    country: 'Costa Rica',
    currency: 'CRC',
    currencyName: 'Costa Rican Colón',
    symbol: '₡',
  },
  {country: 'Cuba', currency: 'CUP', currencyName: 'Cuban Peso', symbol: '$'},
  {
    country: 'Cape Verde',
    currency: 'CVE',
    currencyName: 'Cape Verdean Escudo',
    symbol: '$',
  },
  {
    country: 'Cyprus',
    currency: 'CYP',
    currencyName: 'Cypriot Pound',
    symbol: '£',
  },
  {
    country: 'Czech Republic',
    currency: 'CZK',
    currencyName: 'Czech Koruna',
    symbol: 'Kč',
  },
  {
    country: 'Djibouti',
    currency: 'DJF',
    currencyName: 'Djiboutian Franc',
    symbol: 'Fr',
  },
  {
    country: 'Denmark',
    currency: 'DKK',
    currencyName: 'Danish Krone',
    symbol: 'kr',
  },
  {
    country: 'Dominican Republic',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
    symbol: '$',
  },
  {
    country: 'Algeria',
    currency: 'DZD',
    currencyName: 'Algerian Dinar',
    symbol: 'د.ج',
  },
  {
    country: 'Ecuador',
    currency: 'ECS',
    currencyName: 'Ecuadorian Sucre',
    symbol: 'S/.',
  },
  {
    country: 'Estonia',
    currency: 'EEK',
    currencyName: 'Estonian Kroon',
    symbol: 'kr',
  },
  {
    country: 'Egypt',
    currency: 'EGP',
    currencyName: 'Egyptian Pound',
    symbol: '£',
  },
  {
    country: 'Ethiopia',
    currency: 'ETB',
    currencyName: 'Ethiopian Birr',
    symbol: 'Br',
  },
  {country: 'France', currency: 'EUR', currencyName: 'Euro', symbol: '€'},
  {
    country: 'Fiji',
    currency: 'FJD',
    currencyName: 'Fijian Dollar',
    symbol: '$',
  },
  {
    country: 'Falkland Islands',
    currency: 'FKP',
    currencyName: 'Falkland Islands Pound',
    symbol: '£',
  },
  {
    country: 'United Kingdom',
    currency: 'GBP',
    currencyName: 'British Pound Sterling',
    symbol: '£',
  },
  {
    country: 'Georgia',
    currency: 'GEL',
    currencyName: 'Georgian Lari',
    symbol: '₾',
  },
  {
    country: 'Guernsey',
    currency: 'GGP',
    currencyName: 'Guernsey Pound',
    symbol: '£',
  },
  {
    country: 'Ghana',
    currency: 'GHS',
    currencyName: 'Ghanaian Cedi',
    symbol: '₵',
  },
  {
    country: 'Gibraltar',
    currency: 'GIP',
    currencyName: 'Gibraltar Pound',
    symbol: '£',
  },
  {
    country: 'Gambia',
    currency: 'GMD',
    currencyName: 'Gambian Dalasi',
    symbol: 'D',
  },
  {
    country: 'Guinea',
    currency: 'GNF',
    currencyName: 'Guinean Franc',
    symbol: 'Fr',
  },
  {
    country: 'Guatemala',
    currency: 'GTQ',
    currencyName: 'Guatemalan Quetzal',
    symbol: 'Q',
  },
  {
    country: 'Guyana',
    currency: 'GYD',
    currencyName: 'Guyanese Dollar',
    symbol: '$',
  },
  {
    country: 'Hong Kong',
    currency: 'HKD',
    currencyName: 'Hong Kong Dollar',
    symbol: 'HK$',
  },
  {
    country: 'Honduras',
    currency: 'HNL',
    currencyName: 'Honduran Lempira',
    symbol: 'L',
  },
  {
    country: 'Croatia',
    currency: 'HRK',
    currencyName: 'Croatian Kuna',
    symbol: 'kn',
  },
  {
    country: 'Haiti',
    currency: 'HTG',
    currencyName: 'Haitian Gourde',
    symbol: 'G',
  },
  {
    country: 'Hungary',
    currency: 'HUF',
    currencyName: 'Hungarian Forint',
    symbol: 'Ft',
  },
  {
    country: 'Indonesia',
    currency: 'IDR',
    currencyName: 'Indonesian Rupiah',
    symbol: 'Rp',
  },

  {
    country: 'Iraq',
    currency: 'IQD',
    currencyName: 'Iraqi Dinar',
    symbol: 'ع.د',
  },
  {country: 'Iran', currency: 'IRR', currencyName: 'Iranian Rial', symbol: '﷼'},
  {
    country: 'Iceland',
    currency: 'ISK',
    currencyName: 'Icelandic Króna',
    symbol: 'kr',
  },
  {
    country: 'Jamaica',
    currency: 'JMD',
    currencyName: 'Jamaican Dollar',
    symbol: 'J$',
  },
  {
    country: 'Jordan',
    currency: 'JOD',
    currencyName: 'Jordanian Dinar',
    symbol: 'د.ا',
  },
  {
    country: 'Japan',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
    symbol: '¥',
  },
  {
    country: 'Kenya',
    currency: 'KES',
    currencyName: 'Kenyan Shilling',
    symbol: 'KSh',
  },
  {
    country: 'Kyrgyzstan',
    currency: 'KGS',
    currencyName: 'Kyrgyzstani Som',
    symbol: 'лв',
  },
  {
    country: 'Cambodia',
    currency: 'KHR',
    currencyName: 'Cambodian Riel',
    symbol: '៛',
  },
  {
    country: 'Comoros',
    currency: 'KMF',
    currencyName: 'Comorian Franc',
    symbol: 'CF',
  },
  {
    country: 'North Korea',
    currency: 'KPW',
    currencyName: 'North Korean Won',
    symbol: '₩',
  },
  {
    country: 'South Korea',
    currency: 'KRW',
    currencyName: 'South Korean Won',
    symbol: '₩',
  },
  {
    country: 'Kuwait',
    currency: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    symbol: 'د.ك',
  },
  {
    country: 'Cayman Islands',
    currency: 'KYD',
    currencyName: 'Cayman Islands Dollar',
    symbol: '$',
  },
  {
    country: 'Kazakhstan',
    currency: 'KZT',
    currencyName: 'Kazakhstani Tenge',
    symbol: '₸',
  },
  {country: 'Laos', currency: 'LAK', currencyName: 'Lao Kip', symbol: '₭'},
  {
    country: 'Lebanon',
    currency: 'LBP',
    currencyName: 'Lebanese Pound',
    symbol: 'ل.ل',
  },
  {
    country: 'Sri Lanka',
    currency: 'LKR',
    currencyName: 'Sri Lankan Rupee',
    symbol: '₨',
  },
  {
    country: 'Liberia',
    currency: 'LRD',
    currencyName: 'Liberian Dollar',
    symbol: '$',
  },
  {
    country: 'Lesotho',
    currency: 'LSL',
    currencyName: 'Lesotho Loti',
    symbol: 'L',
  },
  {
    country: 'Lithuania',
    currency: 'LTL',
    currencyName: 'Lithuanian Litas',
    symbol: 'Lt',
  },
  {
    country: 'Latvia',
    currency: 'LVL',
    currencyName: 'Latvian Lats',
    symbol: 'Ls',
  },
  {
    country: 'Libya',
    currency: 'LYD',
    currencyName: 'Libyan Dinar',
    symbol: 'ل.د',
  },
  {
    country: 'Morocco',
    currency: 'MAD',
    currencyName: 'Moroccan Dirham',
    symbol: 'د.م.',
  },
  {
    country: 'Moldova',
    currency: 'MDL',
    currencyName: 'Moldovan Leu',
    symbol: 'L',
  },
  {
    country: 'Madagascar',
    currency: 'MGA',
    currencyName: 'Malagasy Ariary',
    symbol: 'Ar',
  },
  {
    country: 'North Macedonia',
    currency: 'MKD',
    currencyName: 'Macedonian Denar',
    symbol: 'ден',
  },
  {
    country: 'Myanmar',
    currency: 'MMK',
    currencyName: 'Myanmar Kyat',
    symbol: 'K',
  },
  {
    country: 'Mongolia',
    currency: 'MNT',
    currencyName: 'Mongolian Tugrik',
    symbol: '₮',
  },
  {
    country: 'Macau',
    currency: 'MOP',
    currencyName: 'Macanese Pataca',
    symbol: 'MOP$',
  },
  {
    country: 'Mauritania',
    currency: 'MRO',
    currencyName: 'Mauritanian Ouguiya',
    symbol: 'UM',
  },
  {
    country: 'Malta',
    currency: 'MTL',
    currencyName: 'Maltese Lira',
    symbol: '₤',
  },
  {
    country: 'Mauritius',
    currency: 'MUR',
    currencyName: 'Mauritian Rupee',
    symbol: '₨',
  },
  {
    country: 'Maldives',
    currency: 'MVR',
    currencyName: 'Maldivian Rufiyaa',
    symbol: 'Rf',
  },
  {
    country: 'Malawi',
    currency: 'MWK',
    currencyName: 'Malawian Kwacha',
    symbol: 'MK',
  },
  {
    country: 'Mexico',
    currency: 'MXN',
    currencyName: 'Mexican Peso',
    symbol: '$',
  },
  {
    country: 'Malaysia',
    currency: 'MYR',
    currencyName: 'Malaysian Ringgit',
    symbol: 'RM',
  },
  {
    country: 'Mozambique',
    currency: 'MZN',
    currencyName: 'Mozambican Metical',
    symbol: 'MT',
  },
  {
    country: 'Namibia',
    currency: 'NAD',
    currencyName: 'Namibian Dollar',
    symbol: '$',
  },
  {
    country: 'New Caledonia',
    currency: 'XPF',
    currencyName: 'CFP Franc',
    symbol: '₣',
  },
  {
    country: 'Nigeria',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
    symbol: '₦',
  },
  {
    country: 'Nicaragua',
    currency: 'NIO',
    currencyName: 'Nicaraguan Córdoba',
    symbol: 'C$',
  },
  {
    country: 'Nepal',
    currency: 'NPR',
    currencyName: 'Nepalese Rupee',
    symbol: '₨',
  },
  {
    country: 'New Zealand',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
    symbol: '$',
  },
  {
    country: 'Oman',
    currency: 'OMR',
    currencyName: 'Omani Rial',
    symbol: 'ر.ع.',
  },
  {
    country: 'Palestine',
    currency: 'JOD',
    currencyName: 'Jordanian Dinar',
    symbol: 'د.أ',
  },
  {
    country: 'Panama',
    currency: 'PAB',
    currencyName: 'Panamanian Balboa',
    symbol: 'B/.',
  },
  {
    country: 'Peru',
    currency: 'PEN',
    currencyName: 'Peruvian Sol',
    symbol: 'S/.',
  },
  {
    country: 'Papua New Guinea',
    currency: 'PGK',
    currencyName: 'Papua New Guinean Kina',
    symbol: 'K',
  },
  {
    country: 'Philippines',
    currency: 'PHP',
    currencyName: 'Philippine Peso',
    symbol: '₱',
  },
  {
    country: 'Pakistan',
    currency: 'PKR',
    currencyName: 'Pakistani Rupee',
    symbol: '₨',
  },
  {
    country: 'Poland',
    currency: 'PLN',
    currencyName: 'Polish Zloty',
    symbol: 'zł',
  },
  {
    country: 'Paraguay',
    currency: 'PYG',
    currencyName: 'Paraguayan Guarani',
    symbol: '₲',
  },
  {
    country: 'Qatar',
    currency: 'QAR',
    currencyName: 'Qatari Riyal',
    symbol: '﷼',
  },
  {
    country: 'Romania',
    currency: 'RON',
    currencyName: 'Romanian Leu',
    symbol: 'lei',
  },
  {
    country: 'Serbia',
    currency: 'RSD',
    currencyName: 'Serbian Dinar',
    symbol: 'дин.',
  },
  {
    country: 'Russia',
    currency: 'RUB',
    currencyName: 'Russian Ruble',
    symbol: '₽',
  },
  {
    country: 'Rwanda',
    currency: 'RWF',
    currencyName: 'Rwandan Franc',
    symbol: 'FRw',
  },
  {
    country: 'Saudi Arabia',
    currency: 'SAR',
    currencyName: 'Saudi Riyal',
    symbol: '﷼',
  },
  {
    country: 'Solomon Islands',
    currency: 'SBD',
    currencyName: 'Solomon Islands Dollar',
    symbol: '$',
  },
  {
    country: 'Seychelles',
    currency: 'SCR',
    currencyName: 'Seychellois Rupee',
    symbol: '₨',
  },
  {
    country: 'Sudan',
    currency: 'SDG',
    currencyName: 'Sudanese Pound',
    symbol: '£',
  },
  {
    country: 'Sweden',
    currency: 'SEK',
    currencyName: 'Swedish Krona',
    symbol: 'kr',
  },
  {
    country: 'Singapore',
    currency: 'SGD',
    currencyName: 'Singapore Dollar',
    symbol: '$',
  },
  {
    country: 'Slovakia',
    currency: 'SKK',
    currencyName: 'Slovak Koruna',
    symbol: 'Sk',
  }, // No longer used
  {
    country: 'Sierra Leone',
    currency: 'SLL',
    currencyName: 'Sierra Leonean Leone',
    symbol: 'Le',
  },
  {
    country: 'Somalia',
    currency: 'SOS',
    currencyName: 'Somali Shilling',
    symbol: 'Sh',
  },
  {
    country: 'Suriname',
    currency: 'SRD',
    currencyName: 'Surinamese Dollar',
    symbol: '$',
  },
  {
    country: 'São Tomé and Príncipe',
    currency: 'STD',
    currencyName: 'São Tomé and Príncipe Dobra',
    symbol: 'Db',
  },
  {
    country: 'El Salvador',
    currency: 'SVC',
    currencyName: 'Salvadoran Colón',
    symbol: '₡',
  },
  {
    country: 'Syria',
    currency: 'SYP',
    currencyName: 'Syrian Pound',
    symbol: '£',
  },
  {
    country: 'Eswatini',
    currency: 'SZL',
    currencyName: 'Swazi Lilangeni',
    symbol: 'E',
  },
  {
    country: 'Thailand',
    currency: 'THB',
    currencyName: 'Thai Baht',
    symbol: '฿',
  },
  {
    country: 'Tajikistan',
    currency: 'TJS',
    currencyName: 'Tajikistani Somoni',
    symbol: 'ЅМ',
  },
  {
    country: 'Turkmenistan',
    currency: 'TMT',
    currencyName: 'Turkmenistani Manat',
    symbol: 'm',
  },
  {
    country: 'Tunisia',
    currency: 'TND',
    currencyName: 'Tunisian Dinar',
    symbol: 'د.ت',
  },
  {
    country: 'Tonga',
    currency: 'TOP',
    currencyName: 'Tongan Paʻanga',
    symbol: 'T$',
  },
  {
    country: 'Turkey',
    currency: 'TRY',
    currencyName: 'Turkish Lira',
    symbol: '₺',
  },
  {
    country: 'Trinidad and Tobago',
    currency: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
    symbol: '$',
  },
  {
    country: 'Taiwan',
    currency: 'TWD',
    currencyName: 'New Taiwan Dollar',
    symbol: 'NT$',
  },
  {
    country: 'Tanzania',
    currency: 'TZS',
    currencyName: 'Tanzanian Shilling',
    symbol: 'Sh',
  },
  {
    country: 'Ukraine',
    currency: 'UAH',
    currencyName: 'Ukrainian Hryvnia',
    symbol: '₴',
  },
  {
    country: 'Uganda',
    currency: 'UGX',
    currencyName: 'Ugandan Shilling',
    symbol: 'Sh',
  },

  {
    country: 'Uruguay',
    currency: 'UYU',
    currencyName: 'Uruguayan Peso',
    symbol: '$U',
  },
  {
    country: 'Uzbekistan',
    currency: 'UZS',
    currencyName: 'Uzbekistan Som',
    symbol: 'лв',
  },
  {
    country: 'Venezuela',
    currency: 'VEF',
    currencyName: 'Venezuelan Bolívar',
    symbol: 'Bs',
  },
  {
    country: 'Vietnam',
    currency: 'VND',
    currencyName: 'Vietnamese Đồng',
    symbol: '₫',
  },
  {
    country: 'Vanuatu',
    currency: 'VUV',
    currencyName: 'Vanuatu Vatu',
    symbol: 'VT',
  },
  {country: 'Yemen', currency: 'YER', currencyName: 'Yemeni Rial', symbol: '﷼'},
  {
    country: 'South Africa',
    currency: 'ZAR',
    currencyName: 'South African Rand',
    symbol: 'R',
  },
  {
    country: 'Zambia',
    currency: 'ZMK',
    currencyName: 'Zambian Kwacha',
    symbol: 'ZK',
  },
  {
    country: 'Zimbabwe',
    currency: 'ZWD',
    currencyName: 'Zimbabwean Dollar',
    symbol: '$',
  },
];
export default countriesData;
